config/routes.rb
IsTest::Application.routes.draw do

  resources :students
  resources :courses
  get 'classrooms' => 'classroom#index'
  post 'classroom/create' => 'classroom#create'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student, dependent: :destroy
  belongs_to :course, dependent: :destroy

  before_save :define_entry_at

  private
  def define_entry_at
    self.entry_at = DateTime.now
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  #0-Possui vagas abertas
  #1-Lotado
  STATUS = ['Vaga', 'Lotado']

  validates_presence_of :name, :description, :status
  has_many :classrooms
  has_many :students, through: :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base
  STATUS = ['Normal', 'Faltando documentação']

  validates_presence_of :name, :register_number, :status
  has_many :classrooms
  has_many :courses, through: :classrooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classroom_controller.rb
class ClassroomController < ApplicationController
  def index
    @courses = Course.all
    @students = Student.all
  end

  def create
    if classroom_params[:course_id].nil?
      redirect_to :courses, notice: 'Necessário cadastrar um curso'
    elsif classroom_params[:student].nil?
      redirect_to :students, notice: 'Necessário cadastrar um Aluno'
    else
      Classroom.create classroom_params
      redirect_to :courses, notice: 'Matricula criada com sucesso'
    end
  end

  private
  def classroom_params
    {student_id: params[:student], course_id: params[:course]}
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:status, :description, :name)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new

    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:status, :register_number, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classroom/index.html.erb
<h1>New course</h1>

<%= form_tag('/classroom/create') do %>
    <div class="control-group">
      <label class="control-label">Curso:</label>
      <div class="controls">
        <%= select_tag 'course', options_for_select(@courses.collect{|c|[c.name, c.id]})%>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Estudante:</label>
      <div class="controls">
        <%= select_tag 'student', options_for_select(@students.collect{|c|[c.name, c.id]})%>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag 'Salvar', :class => 'btn btn-primary' %>
      <%= link_to 'Voltar', courses_path, class: 'btn' %>
    </div>

<% end %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
    <input type="hidden" name="exams[]" value="[]" id="exams">
    <% if @course.errors.any? %>
        <div class="alert alert-error">
          <ul>
            <% @course.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <label class="control-label">Nome:</label>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Descrição:</label>
      <div class="controls">
        <%= f.text_field :description %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Status:</label>
      <div class="controls">
        <%= f.text_field :status %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
      <%= link_to 'Voltar', students_path, class: 'btn' %>
    </div>
<% end %>
</fieldset>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Cursos</h1>

<%= link_to 'Novo Curso', new_course_path, class: 'btn btn-info' %>

<table class="table">
  <thead>
  <tr>
    <th>nome</th>
    <th>Descrição</th>
    <th>Status</th>
    <th>Studantes</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= Course::STATUS[course.status] %></td>
        <td><%= course.students.collect{|s| s.name}.join(',')%></td>
        <td>
          <div class="btn-group">
            <button class="btn"><%= link_to 'Editar', edit_course_path(course) %></button>
            <button class="btn"><%= link_to 'Apagar', course, method: :delete, data: { confirm: 'Quer realmente apagar?' } %></button>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Escola" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Escola</a>
      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <li><%= link_to "Alunos", "/students"  %></li>
          <li><%= link_to "Cursos", "/courses"  %></li>
          <li><%= link_to "Aulas", "/classrooms"  %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

</div> <!-- /container -->

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
    <input type="hidden" name="exams[]" value="[]" id="exams">
    <% if @student.errors.any? %>
        <div class="alert alert-error">
          <ul>
            <% @student.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <label class="control-label">Nome:</label>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Matricula:</label>
      <div class="controls">
        <%= f.text_field :register_number %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Status:</label>
      <div class="controls">
        <%= f.text_field :status %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
      <%= link_to 'Voltar', students_path, class: 'btn' %>
    </div>
<% end %>
</fieldset>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Estudantes</h1>

<%= link_to 'Novo Estudante', new_student_path, class: 'btn btn-info' %>

<table class="table">
  <thead>
  <tr>
    <th>nome</th>
    <th>Matricula</th>
    <th>Status</th>
    <th>Cursos</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td><%= Student::STATUS[student.status] %></td>
        <td><%= student.courses.collect{|c| c.name}.join(',')%></td>
        <td>
          <div class="btn-group">
            <button class="btn"><%= link_to 'Editar', edit_student_path(student) %></button>
            <button class="btn"><%= link_to 'Apagar', student, method: :delete, data: { confirm: 'Quer realmente apagar?' } %></button>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>